name: Close old issues that need reply

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: needs-reply

jobs:
  needs-reply:
    runs-on: ubuntu-latest
    if: github.repository == 'capawesome-team/capacitor-firebase'
    steps:
      - name: Close old issues that need reply
        uses: dwieeb/needs-reply@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-label: 'needs: reply'
