name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - development
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - 'docs/**'

env:
  NODE_VERSION: 20
  JAVA_VERSION: 21
  TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}

jobs:
  test-android:
    name: Test Android platform
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: oven-sh/setup-bun@v2
      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Install dependencies
        run: bun i
      - name: Build packages affected by changes
        if: github.ref != 'refs/heads/main'
        run: bun run affected:verify:android
      - name: Build all packages
        if: github.ref == 'refs/heads/main'
        run: bun run verify:android

  test-ios:
    name: Test iOS platform
    runs-on: macos-15
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: oven-sh/setup-bun@v2
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      - name: Install dependencies
        run: bun i
      - name: Install CocoaPods dependencies of packages affected by changes
        if: github.ref != 'refs/heads/main'
        run: bun run affected:ios:pod:install
      - name: Install all CocoaPods dependencies
        if: github.ref == 'refs/heads/main'
        run: bun run ios:pod:install
      - name: Install SPM dependencies of packages affected by changes
        if: github.ref != 'refs/heads/main'
        run: bun run affected:ios:spm:install
      - name: Install all SPM dependencies
        if: github.ref == 'refs/heads/main'
        run: bun run ios:spm:install
      - name: Build packages affected by changes
        if: github.ref != 'refs/heads/main'
        run: bun run affected:verify:ios
      - name: Build all packages
        if: github.ref == 'refs/heads/main'
        run: bun run verify:ios

  test-web:
    name: Test Web platform
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i
      - name: Build packages affected by changes
        if: github.ref != 'refs/heads/main'
        run: bun run affected:verify:web
      - name: Build all packages
        if: github.ref == 'refs/heads/main'
        run: bun run verify:web

  lint:
    name: Lint
    runs-on: macos-15
    needs: [test-android, test-ios, test-web]
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i
      - name: Lint packages affected by changes
        if: github.ref != 'refs/heads/main'
        run: bun run affected:lint
      - name: Lint all packages
        if: github.ref == 'refs/heads/main'
        run: bun run lint
